# Generated by Django 2.2 on 2021-05-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
